// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiml8NJswPuYq5n38hyYhaDU0RbUBxCdU',
    appId: '1:842849884691:web:1595f0ffae1952af35fde6',
    messagingSenderId: '842849884691',
    projectId: 'ititraining-1',
    authDomain: 'ititraining-1.firebaseapp.com',
    storageBucket: 'ititraining-1.appspot.com',
    measurementId: 'G-EW250F2HXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7HxMLEtmtROJWxjwNPKlVJeSoIiEPiEM',
    appId: '1:842849884691:android:aa2ef087fac36a9f35fde6',
    messagingSenderId: '842849884691',
    projectId: 'ititraining-1',
    storageBucket: 'ititraining-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTHiFSsahOkZ8cwa7H0Hh7zSdOLYhBI5k',
    appId: '1:842849884691:ios:a41f8220ac3b92b335fde6',
    messagingSenderId: '842849884691',
    projectId: 'ititraining-1',
    storageBucket: 'ititraining-1.appspot.com',
    iosClientId: '842849884691-v2vglbebkr00kudfsgemmkhn1usu599g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTHiFSsahOkZ8cwa7H0Hh7zSdOLYhBI5k',
    appId: '1:842849884691:ios:bc1de9b28046a38435fde6',
    messagingSenderId: '842849884691',
    projectId: 'ititraining-1',
    storageBucket: 'ititraining-1.appspot.com',
    iosClientId: '842849884691-qqb4d50fdvl3ef8dfd57kpg6rjggcru2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
